### PR TITLE
Restrict FFTs in DistributedFNOBlock

### PR DESCRIPTION
**Pull request by Infinoid**
DFNO only applies weights to the low frequencies, and zeroes out the rest.  Discarding them entirely should reduce the amount of FFT work, and the amount of network transfer that distdl needs to do.

3 commits in this PR, for ease of review:

1. remove trailing whitespace (my text editor was picky about it)
2. convert multi-dimensional fft calls to individual calls for each dimension
3. apply restrictions after each fft, and zero-pad tensors prior to each ifft

I tested this by adding code to `benchmarks/bench.py` to dump tensors to disk, and comparing the data with and without these patches.  The fftn-to-fft patch seems to affect the data by about `1e-10`.  The other patches have no effect.

I ran it with and without `--benchmark-type`, on 1, 2 and 4 MPI processes.  It seems to work.  But on 4 processes, I had to be very careful about sizes, partitions and modes to make sure the load balance didn't change before and after.  (More details in comments below.)

TODO:
- [x] fix slice handling when run with multiple MPI ranks

### CODE REVIEW

**Comment by Infinoid** [comment]
In the first version of this, I had confused a couple of things:

1.  Which parts of the (global) data to keep when doing restriction
2.  Which parts of the (local) data to apply weights to

`self.slices` is #<span/>2, and I tried to use it for #<span/>1 as well.  But that only works on a single process, because local=global in that case.  The code needs to treat those two things as separate.  I'm working to fix this, and will update this PR once it works.

**Comment by Infinoid** [comment]
While testing this on 4 MPI processes, I found that load imbalance is quite common, and this restriction patch affects that.

For example, if the dimension 4 size is 32 and the modes is 4, then the layout across 4 MPI ranks might be:
```
dataset:       0405 0607 1415 1617 2425 2627 3435 3637
distdl:       | rank 0  | rank 1  | rank 2  | rank 3  |
weights:       abcd      (empty)   (empty)        efgh
```

So all of the weights are on ranks 0 and 3, and ranks 1-2 had no work to do.

After the patch, the buffer size has been restricted to 8 before calling the `Repartition`, and distdl lays it out differently.  After the patch, it looks more like this:

```
restricted:    04 05 36 37
distdl:       |r0|r1|r2|r3|
weights:       ab cd ef gh
```

Which sounds like a good thing, I think.  But it did make it trickier to test, since the randomly generated weights are different - each rank has its own RNG, and the number of times they call it has changed.  I had to choose a specific shape and number of modes that didn't have any load imbalance, so that the data distribution still lines up and the data is comparable.

**Comment by mloubout** [comment]
>since the randomly generated weights are different - each rank has its own RNG

THis can be easily bypassed setting a fixed seed everywhere with `torch.manual_seed(some-number)` so that they all use the same random seed (and therefore weights)

**Comment by Infinoid** [comment]
> THis can be easily bypassed setting a fixed seed everywhere with `torch.manual_seed(some-number)` so that they all use the same random seed (and therefore weights)

True, good idea.  I did this, but it doesn't help when the distribution of weights changes.  The restriction affects the load imbalance.

Before patch:
* rank 0 has 4 weights
* rank 1 has 0 weights
* rank 2 has 0 weights
* rank 3 has 4 weights

After patch:
* rank 0 has 2 weights
* rank 1 has 2 weights
* rank 2 has 2 weights
* rank 3 has 2 weights

A fixed RNG seed isn't enough to make these two distributions consistent.  This is what I was trying to describe with the bad ascii art, above... sorry if it wasn't clear.

**Comment by thomasjgrady** [comment]
Apologies for the delay on this. PR approved.

**Pull request merged**
