### PR TITLE
Remove autogenerated `dfno.egg-info` folder

### PR DESCRIPTION
**Pull request by Infinoid**
The files in `dfno.egg-info/` appear to be automatically created by `pip install`.  This happened a while ago, and the version number, dependencies and list of source files have changed since then.  So, the metadata changes whenever I try to `pip install` it.

This patch updates the metadata.  Alternately, you might consider removing the `dfno.egg-info/` folder from git, since it is autogenerated by pip.

### CODE REVIEW

**Comment by mloubout** [comment]
the `egg-info` should definitely not be in there, that's a mistake that was committed by error. Should be removed

**Comment by Infinoid** [comment]
Ok, I updated this PR to remove the folder instead.

**Comment by Infinoid** [comment]
Sorry about the spam, I just remembered to update the commit message too.

**Comment by mloubout** [comment]
No worries all good thanks.

**Pull request merged**
